### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by jmmyfam** [nss-evening-cohort-27/gitsub-super-awesome-team-name#6]
- [ ] 1. Data for pending projects table:
- [ ] - overview {
- [ ]   link string
- [ ]   language string 
- [ ]   status string
- [ ] }
- [ ] 
- [ ] 2. Loop thru the data and render cards 

3. Create form with 2 input fields and a button

**Comment by mkcarter7** [comment]
STRETCH GOALS:
Allow users to Delete Pins
Create the About area shown in the Wireframe

**Comment by asparadise33** [comment]
1. Data displays all your pinned repos
2. form with two inputs: new project/description - will need to push new pinned project to the array 
3. needs profile/navbar/footer
