### ISSUE TITLE
Repositories Tab

### ISSUE THREAD

**Issue by jmmyfam** [nss-evening-cohort-27/gitsub-super-awesome-team-name#7]
1. Create data for different repos 
2. Loop thru data and render to DOM into a row
3. Form to add new repo

**Comment by mkcarter7** [comment]
STRETCH GOAL:
Allow users to search through the repos using the search bar
Allow users to Star Repos

**Comment by asparadise33** [comment]
1. Needs a data loop for different repos to be displayed
2. needs a form with two inputs: repository name/description - form needs to push to the new repo to established array
3. needs profile/navbar/footer
