### ISSUE TITLE
Projects Tab

### ISSUE THREAD

**Issue by jmmyfam** [nss-evening-cohort-27/gitsub-super-awesome-team-name#8]
1. Create data for projects
2. Loop thru data and render to DOM 
3. Form

**Comment by asparadise33** [comment]
Project page Requirements:

1. Needs minimum 5 projects listed on the page (this is your data loop) 
2. Needs a search bar 
3. Needs a form that has two inputs (project name and project description) for a new project to be added with a submit button 
4. will need the side profile, navbar, footer

**Comment by mkcarter7** [comment]
STRETCH GOALS:
Allow users to search through the projects using the search bar
Allow users to sort using the sort tool in the wireframe
