### ISSUE TITLE
Packages Page

### ISSUE THREAD

**Issue by jmmyfam** [nss-evening-cohort-27/gitsub-super-awesome-team-name#9]
1. Data for packages
2. loop thru data & render
3. Form to add new package

**Comment by asparadise33** [comment]
1.  Will have a list of packages, and our data will loop through the packages - and our form will add a new package to our array
2. needs a form with two inputs
3. Needs navbar/profile/footer

**Comment by mkcarter7** [comment]
STRETCH GOAL:
Allow users to Delete Packages
Allow users to search packages
